# ==============================================================================
# AI GOVERNANCE STRATEGIC TERRAIN
# Sanitized public publication-style visualization
#
# Reproduces the public-facing strategic-terrain figure from the PCoA baseline
# generated by analysis/01_pcoa_process_terrain.R.
#
# This script intentionally does NOT claim to reproduce private evidence panels,
# actor-position source files, bootstrap studies, influence estimates, or other
# non-public analytical layers from the broader working project.
# ==============================================================================

required_pkgs <- c("tidyverse", "ggplot2", "ggforce", "ggrepel", "scales")
missing_pkgs <- required_pkgs[!vapply(required_pkgs, requireNamespace, quietly = TRUE, FUN.VALUE = logical(1))]
if (length(missing_pkgs) > 0) {
  stop(
    "Install required packages before running this script: ",
    paste(missing_pkgs, collapse = ", ")
  )
}

library(tidyverse)
library(ggplot2)
library(ggforce)
library(ggrepel)
library(scales)

PCOA_FILE <- file.path("pcoa_outputs", "pcoa_coordinates.csv")
ACTOR_VENUE_FILE <- file.path("data", "actor_venue_involvement.csv")
FIGURE_DIR <- "figures"

if (!file.exists(PCOA_FILE)) {
  stop(
    "Missing ", PCOA_FILE, ". Run analysis/01_pcoa_process_terrain.R first."
  )
}
if (!dir.exists(FIGURE_DIR)) dir.create(FIGURE_DIR, recursive = TRUE)

navy <- "#0B1F4D"
agenda_col <- "#2457E6"
tech_col <- "#147A34"
norms_col <- "#6A34C5"
develop_col <- "#F05A18"
us_col <- "#2457E6"
china_col <- "#E3262E"
eu_col <- "#6A34C5"
g77_col <- "#F05A18"
other_col <- "#666666"
context_col <- "#9AA3B2"

pcoa <- read_csv(PCOA_FILE, show_col_types = FALSE)
stopifnot(all(c("venue", "PCoA1", "PCoA2") %in% names(pcoa)))

venue_layout <- tribble(
  ~venue,                ~label,       ~group,        ~entity_type,  ~x_fallback, ~y_fallback, ~size, ~observability,
  "UN",                  "UN",         "agenda",      "institution", 3.10,        6.80,        18.0,  "high",
  "GDC",                 "GDC",        "agenda",      "process",     4.35,        6.95,        10.0,  "high",
  "Dialogue",            "Dialogue",   "agenda",      "process",     2.25,        5.70,         7.8,  "medium",
  "AI Panel / Dialogue", "AI\nPanel",  "agenda",      "process",     3.95,        5.45,         8.2,  "low",
  "ITU",                 "ITU",        "technical",   "institution", 6.90,        6.90,        16.0,  "high",
  "ITU C24/85",          "C24/85",     "technical",   "process",     8.30,        7.00,         7.8,  "high",
  "WSIS+20",             "WSIS",       "technical",   "process",     7.75,        5.45,        10.0,  "high",
  "UNESCO",              "UNESCO",     "norms",       "institution", 2.95,        3.40,        15.0,  "high",
  "UNESCO AI Ethics",    "AI\nEthics", "norms",       "process",     3.95,        3.35,         8.2,  "medium",
  "CSTD 29",             "CSTD",       "development", "institution", 7.45,        3.35,        14.0,  "medium"
)

pcoa_use <- pcoa |>
  filter(venue %in% venue_layout$venue) |>
  transmute(
    venue,
    x_data = rescale(PCoA1, to = c(3.75, 8.20)),
    y_data = rescale(PCoA2, to = c(3.25, 7.00))
  )

venue_layout <- venue_layout |>
  left_join(pcoa_use, by = "venue") |>
  mutate(
    x = coalesce(x_data, x_fallback),
    y = coalesce(y_data, y_fallback)
  ) |>
  select(-x_data, -y_data)

# Standing institutions are visual anchors rather than PCoA observations.
parent_anchor_positions <- tribble(
  ~venue,   ~x_parent, ~y_parent,
  "UN",      3.10,      6.80,
  "ITU",     6.90,      6.90,
  "UNESCO",  2.95,      3.40
)

venue_layout <- venue_layout |>
  left_join(parent_anchor_positions, by = "venue") |>
  mutate(
    x = coalesce(x_parent, x),
    y = coalesce(y_parent, y)
  ) |>
  select(-x_parent, -y_parent, -x_fallback, -y_fallback)

halo_df <- tribble(
  ~group,        ~x0,  ~y0,  ~a,   ~b,   ~angle,
  "agenda",       3.45, 6.25, 1.78, 1.35, -10,
  "technical",    7.35, 6.20, 1.75, 1.45,   5,
  "norms",        3.35, 3.40, 1.55, 1.10,   5,
  "development",  7.45, 3.35, 1.25, 1.05,   0
)

halo_labels <- tribble(
  ~group,        ~x,    ~y,   ~label,
  "agenda",       3.55, 7.92, "Agenda & Legitimacy",
  "technical",    7.55, 7.92, "Technical & Implementation",
  "norms",        3.35, 4.70, "Norms & Rights",
  "development",  7.45, 4.70, "Development & Capacity"
)

group_fill <- c(
  agenda = agenda_col,
  technical = tech_col,
  norms = norms_col,
  development = develop_col
)

relationships <- tribble(
  ~from,    ~to,
  "UN",     "GDC",
  "UN",     "Dialogue",
  "UN",     "AI Panel / Dialogue",
  "ITU",    "ITU C24/85",
  "ITU",    "WSIS+20",
  "UNESCO", "UNESCO AI Ethics"
) |>
  left_join(
    venue_layout |> select(from = venue, x_from = x, y_from = y),
    by = "from"
  ) |>
  left_join(
    venue_layout |> select(to = venue, x_to = x, y_to = y),
    by = "to"
  )

context_nodes <- tribble(
  ~name,        ~x,    ~y,
  "AU",          0.80, 5.95,
  "ASEAN",       0.75, 4.35,
  "WHO",        10.15, 6.75,
  "OECD",       10.55, 5.30,
  "G7",         10.20, 3.75,
  "BRICS",       2.40, 1.70,
  "WAICO",       5.20, 1.45,
  "Pax Silica",  6.85, 1.45
)

country_fallback <- tribble(
  ~actor,              ~actor_group, ~x,    ~y,   ~evidence,
  "United States",     "US",          5.65, 6.90, "high",
  "United Kingdom",    "US",          5.05, 6.20, "high",
  "France",            "US",          4.60, 5.45, "medium",
  "Germany",           "Other",       5.55, 5.10, "medium",
  "European Union",    "EU",          4.35, 4.95, "high",
  "Switzerland",       "Other",       4.15, 4.15, "high",
  "Japan",             "Other",       8.95, 6.25, "high",
  "Republic of Korea", "Other",       8.95, 5.55, "high",
  "India",             "G77",         6.90, 5.10, "medium",
  "China",             "China",       9.05, 4.85, "high",
  "Russia",            "Other",       9.45, 4.05, "high",
  "G77+China",         "G77",         6.40, 4.25, "high",
  "Brazil",            "G77",         6.15, 3.55, "medium",
  "South Africa",      "G77",         6.75, 3.40, "low"
)

if (file.exists(ACTOR_VENUE_FILE)) {
  actor_venue <- read_csv(ACTOR_VENUE_FILE, show_col_types = FALSE)
  required_cols <- c("actor", "venue", "involvement_weight", "evidence_breadth")
  stopifnot(all(required_cols %in% names(actor_venue)))

  actor_group_lookup <- country_fallback |>
    select(actor, actor_group) |>
    distinct()

  country_df <- actor_venue |>
    mutate(involvement_weight = pmax(0, involvement_weight)) |>
    left_join(
      venue_layout |> select(venue, venue_x = x, venue_y = y),
      by = "venue"
    ) |>
    filter(!is.na(venue_x), !is.na(venue_y), involvement_weight > 0) |>
    group_by(actor) |>
    summarise(
      x = weighted.mean(venue_x, involvement_weight, na.rm = TRUE),
      y = weighted.mean(venue_y, involvement_weight, na.rm = TRUE),
      evidence = first(evidence_breadth),
      .groups = "drop"
    ) |>
    left_join(actor_group_lookup, by = "actor") |>
    mutate(actor_group = coalesce(actor_group, "Other"))
} else {
  country_df <- country_fallback
}

country_label_overrides <- c(
  "United States" = "U.S.",
  "United Kingdom" = "U.K.",
  "Republic of Korea" = "Republic\nof Korea",
  "G77+China" = "G77+China"
)

country_df <- country_df |>
  mutate(
    evidence_alpha = case_when(
      evidence == "high" ~ 1.00,
      evidence == "medium" ~ 0.72,
      TRUE ~ 0.45
    ),
    actor_color = case_when(
      actor_group == "US" ~ us_col,
      actor_group == "China" ~ china_col,
      actor_group == "EU" ~ eu_col,
      actor_group == "G77" ~ g77_col,
      TRUE ~ other_col
    ),
    display = if_else(
      actor %in% names(country_label_overrides),
      country_label_overrides[actor],
      actor
    )
  )

obs_lty <- c(high = "solid", medium = "22", low = "13")

p <- ggplot() +
  ggforce::geom_ellipse(
    data = halo_df,
    aes(x0 = x0, y0 = y0, a = a, b = b, angle = angle * pi / 180, fill = group),
    color = NA,
    alpha = 0.20,
    inherit.aes = FALSE
  ) +
  geom_segment(
    data = relationships,
    aes(x = x_from, y = y_from, xend = x_to, yend = y_to),
    linewidth = 0.45,
    color = alpha("#586174", 0.36)
  ) +
  geom_point(
    data = context_nodes,
    aes(x = x, y = y),
    shape = 21,
    size = 14,
    stroke = 0.65,
    fill = "white",
    color = alpha(context_col, 0.42)
  ) +
  geom_text(
    data = context_nodes,
    aes(x = x, y = y, label = name),
    size = 3.8,
    color = alpha("#526075", 0.58)
  ) +
  geom_point(
    data = venue_layout,
    aes(x = x, y = y, size = size, color = group, linetype = observability),
    shape = 21,
    fill = "white",
    stroke = 1.6
  ) +
  geom_point(
    data = venue_layout |> filter(entity_type == "institution"),
    aes(x = x, y = y, size = size, color = group),
    shape = 21,
    fill = NA,
    stroke = 0.55
  ) +
  geom_text(
    data = venue_layout,
    aes(x = x, y = y, label = label),
    fontface = "bold",
    size = 4.2,
    color = "#111111",
    lineheight = 0.88
  ) +
  geom_text(
    data = halo_labels,
    aes(x = x, y = y, label = label, color = group),
    fontface = "bold",
    size = 5.0
  ) +
  geom_point(
    data = country_df,
    aes(x = x, y = y, alpha = evidence_alpha),
    shape = 23,
    size = 5.5,
    stroke = 1.05,
    fill = country_df$actor_color,
    color = country_df$actor_color
  ) +
  ggrepel::geom_text_repel(
    data = country_df,
    aes(x = x, y = y, label = display, color = actor_group, alpha = evidence_alpha),
    fontface = "bold",
    size = 3.25,
    box.padding = 0.22,
    point.padding = 0.20,
    min.segment.length = 0.05,
    segment.color = alpha("#7A8492", 0.30),
    segment.size = 0.25,
    seed = 20260909,
    max.overlaps = Inf
  ) +
  annotate(
    "text",
    x = 6.00,
    y = 1.88,
    label = "Emerging architectures — contextual, not statistically embedded",
    fontface = "italic",
    size = 3.6,
    color = alpha("#4E5764", 0.75)
  ) +
  labs(
    title = "AI Governance Is Strategic Terrain, Not a Single Forum",
    subtitle = paste0(
      "Venue position = process-profile similarity from the public PCoA baseline.  ",
      "Country positions use optional participation weights when supplied, otherwise documented fallback positions.\n",
      "Distances indicate similarity in coded process-evidence profiles, not influence or political alignment."
    ),
    caption = paste0(
      "Public reproducibility layer: structural mixed-data Gower distance · ",
      "Lingoes-corrected PCoA dimensions 1–2 = 66.9%.  ",
      "Functional halos and contextual nodes are descriptive presentation layers."
    )
  ) +
  scale_fill_manual(values = group_fill, guide = "none") +
  scale_color_manual(
    values = c(
      agenda = agenda_col,
      technical = tech_col,
      norms = norms_col,
      development = develop_col,
      US = us_col,
      China = china_col,
      EU = eu_col,
      G77 = g77_col,
      Other = other_col
    ),
    breaks = c("US", "China", "EU", "G77", "Other"),
    labels = c("U.S. and partners", "China", "European Union", "G77+China / partners", "Other actors"),
    name = "Actor grouping"
  ) +
  scale_linetype_manual(
    values = obs_lty,
    breaks = c("high", "medium", "low"),
    labels = c("High observability", "Partial observability", "Evidence-constrained"),
    name = "Observability"
  ) +
  scale_size_identity() +
  scale_alpha_identity() +
  coord_cartesian(xlim = c(0.15, 11.15), ylim = c(1.05, 8.55), clip = "off") +
  theme_void(base_family = "sans") +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    plot.title = element_text(family = "serif", face = "bold", color = navy, size = 25, margin = margin(b = 5)),
    plot.subtitle = element_text(face = "italic", color = "#26364E", size = 11.4, lineheight = 1.18, margin = margin(b = 8)),
    plot.caption = element_text(face = "italic", color = "#26364E", size = 9.4, hjust = 0.5, margin = margin(t = 8)),
    plot.margin = margin(16, 26, 14, 20),
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.box.just = "center"
  )

out_png <- file.path(FIGURE_DIR, "AI_Governance_Strategic_Terrain_Public.png")
out_pdf <- file.path(FIGURE_DIR, "AI_Governance_Strategic_Terrain_Public.pdf")
out_svg <- file.path(FIGURE_DIR, "AI_Governance_Strategic_Terrain_Public.svg")

ggsave(out_png, plot = p, width = 16, height = 10, units = "in", dpi = 400, bg = "white")
ggsave(out_pdf, plot = p, width = 16, height = 10, units = "in", device = cairo_pdf, bg = "white")
ggsave(out_svg, plot = p, width = 16, height = 10, units = "in", device = "svg", bg = "white")

message("Saved public strategic-terrain figures under: ", normalizePath(FIGURE_DIR, mustWork = FALSE))
